name: sast-semgrep-ce
description: "Execute SAST scan using Semgrep CE"

runs:
    steps:
        # Install Semgrep CE
        - name: Install Semgrep
          run: pip install semgrep

        # Run Semgrep CE SAST scan and export results as Sarif file - Semgrep CE only executes a minimal SAST scan
        - name: Run Semgrep SAST scan
          run: semgrep scan --config "p/java" --sarif --sarif-output sarif/${{ github.event.repository.name }}-semgrep-ce-sast-${{ github.run_number }}.sarif

        # Archive the SAST report
        - name: Archive SAST results as Sarif file
          uses: actions/upload-artifact@v4
          with:
              name: semgrepSAST-${{ github.run_number }}.sarif
              path: sarif/${{ github.event.repository.name }}-semgrep-ce-sast-${{ github.run_number }}.sarif
              retention-days: 5

        # Upload SAST report to GitHub Security
        - name: Upload SAST report to GitHub Security
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: sarif/${{ github.event.repository.name }}-semgrep-ce-sast-${{ github.run_number }}.sarif
