name: sca-snyk
description: "Execute SCA scan using Sync"

runs:
    permissions:
        security-events: write
    steps:
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/maven-3-jdk-21@master
          continue-on-error: true # To make sure that SARIF upload gets called
          env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
              args: --sarif-file-output=sarif/${{ github.event.repository.name }}-sca-snyk-${{ github.run_number }}.sarif

        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v4
          with:
              sarif_file: sarif/${{ github.event.repository.name }}-sca-snyk-${{ github.run_number }}.sarif

        - name: Archive code coverage results
          uses: actions/upload-artifact@v4
          with:
              name: sca-snyk.sarif
              path: sarif/${{ github.event.repository.name }}-sca-snyk-${{ github.run_number }}.sarif
              retention-days: 5
